import { db } from '@/lib/db'
import { trainingModules } from '@/lib/db/schema/training'
import { eq } from 'drizzle-orm'

const SEC_AWARENESS_CONTENT = [
  '## Introduction to Security Awareness',
  '',
  'Security awareness is the foundation of every effective cybersecurity program. As an employee, you are often the last line of defense against cyber threats. Understanding how attackers operate and what you can do to stop them is critical to protecting your organization.',
  '',
  'In this module, you will learn about the most common types of threats, how to identify suspicious activity, and the steps you can take to keep information secure.',
  '',
  '## Common Cyber Threats',
  '',
  'Cyber threats come in many forms. The most prevalent include:',
  '',
  '- **Malware**: Software designed to disrupt, damage, or gain unauthorized access to systems. Types include viruses, ransomware, spyware, and trojans.',
  '- **Phishing**: Deceptive emails or messages that trick users into revealing credentials or clicking malicious links.',
  '- **Social Engineering**: Manipulation tactics that exploit human psychology to gain access to systems or information.',
  '- **Insider Threats**: Risks that originate from within the organization, either through malicious intent or accidental actions.',
  '- **Man-in-the-Middle Attacks**: Interception of communications between two parties without their knowledge.',
  '',
  'Recognizing these threats is the first step toward preventing them.',
  '',
  '## Protecting Sensitive Data',
  '',
  'Data protection is a shared responsibility. Follow these practices to keep sensitive information safe:',
  '',
  '1. **Classify data appropriately** — Know which data is confidential, internal, or public and handle it accordingly.',
  '2. **Use strong, unique passwords** — Never reuse passwords across systems. Use a password manager.',
  '3. **Enable multi-factor authentication (MFA)** — Always enable MFA on accounts that support it.',
  '4. **Lock your screen** — Press Win+L or Cmd+Ctrl+Q when stepping away from your workstation.',
  '5. **Avoid public Wi-Fi for work** — Use a VPN if you must connect from untrusted networks.',
  '',
  '## Incident Reporting',
  '',
  'Reporting suspicious activity quickly limits damage. If you suspect a security incident:',
  '',
  '1. Do not attempt to investigate or resolve it yourself.',
  '2. Immediately notify your IT or security team via the designated channel.',
  '3. Preserve evidence — do not delete emails, files, or logs.',
  '4. Document what you observed, including timestamps and any actions you took.',
  '',
  'Early reporting is always better than late reporting, even if you are unsure whether an event is truly malicious.',
  '',
  '## Security at Home',
  '',
  'Remote work extends your organization\'s security perimeter into your home. Apply the same security standards at home as you would in the office:',
  '',
  '- Keep your home router firmware updated and use WPA3 encryption.',
  '- Separate work devices from personal devices and home IoT devices.',
  '- Ensure your home network uses a strong, unique Wi-Fi password.',
  '- Never allow family members to use work devices.',
].join('\n')

const GDPR_CONTENT = [
  '## What is GDPR?',
  '',
  'The General Data Protection Regulation (GDPR) is a comprehensive data protection law enacted by the European Union that came into force on May 25, 2018. It applies to any organization that processes the personal data of EU residents, regardless of where the organization is based.',
  '',
  'GDPR establishes clear rules about how personal data must be collected, stored, used, and protected. Non-compliance can result in fines of up to 20 million EUR or 4% of annual global turnover, whichever is higher.',
  '',
  '## Key Definitions',
  '',
  'Understanding GDPR starts with knowing its key terms:',
  '',
  '- **Personal Data**: Any information that can identify a natural person — name, email, IP address, location data, biometric data, etc.',
  '- **Data Subject**: The individual whose personal data is being processed.',
  '- **Data Controller**: The entity that determines the purpose and means of processing personal data.',
  '- **Data Processor**: An entity that processes data on behalf of the controller.',
  '- **Processing**: Any operation performed on personal data — collection, storage, retrieval, use, disclosure, or deletion.',
  '',
  '## Lawful Bases for Processing',
  '',
  'GDPR requires a lawful basis for every processing activity. The six lawful bases are:',
  '',
  '1. **Consent** — The data subject has given clear, informed consent.',
  '2. **Contract** — Processing is necessary for a contract with the data subject.',
  '3. **Legal Obligation** — Processing is required by law.',
  '4. **Vital Interests** — Processing is necessary to protect someone\'s life.',
  '5. **Public Task** — Processing is necessary for a public interest task.',
  '6. **Legitimate Interests** — Processing is necessary for the controller\'s legitimate interests, balanced against the individual\'s rights.',
  '',
  '## Data Subject Rights',
  '',
  'GDPR grants individuals significant rights over their personal data:',
  '',
  '- **Right to Access**: Individuals can request a copy of their personal data.',
  '- **Right to Rectification**: Individuals can request corrections to inaccurate data.',
  '- **Right to Erasure ("Right to be Forgotten")**: Individuals can request deletion of their data.',
  '- **Right to Restrict Processing**: Individuals can limit how their data is used.',
  '- **Right to Data Portability**: Individuals can receive their data in a machine-readable format.',
  '- **Right to Object**: Individuals can object to processing based on legitimate interests or for direct marketing.',
  '',
  'Organizations must respond to data subject requests within 30 days.',
  '',
  '## Data Breach Response',
  '',
  'If a personal data breach occurs, GDPR requires:',
  '',
  '1. **Internal notification within 24 hours** of becoming aware of the breach.',
  '2. **Supervisory authority notification within 72 hours** if the breach is likely to result in a risk to individuals\' rights and freedoms.',
  '3. **Data subject notification without undue delay** if the breach is likely to result in a high risk to their rights and freedoms.',
  '',
  'A breach does not always mean a cyberattack — it includes accidental loss, unauthorized access, or unauthorized disclosure of personal data.',
].join('\n')

const SOC2_CONTENT = [
  '## SOC 2 Overview for Technical Teams',
  '',
  'SOC 2 (System and Organization Controls 2) is an auditing framework developed by the American Institute of CPAs (AICPA). It evaluates how organizations manage customer data based on five Trust Service Criteria (TSC): Security, Availability, Processing Integrity, Confidentiality, and Privacy.',
  '',
  'For engineering teams, SOC 2 compliance means implementing and maintaining specific technical controls that auditors can verify through evidence.',
  '',
  '## The Five Trust Service Criteria',
  '',
  '### Security (Common Criteria — Required)',
  '',
  'The Security criterion is the only mandatory TSC. It covers logical and physical access controls, system monitoring, and risk mitigation. Key engineering requirements:',
  '',
  '- Implement role-based access control (RBAC) across all systems.',
  '- Enforce MFA on all production access — including cloud consoles, code repositories, and VPNs.',
  '- Encrypt data at rest (AES-256) and in transit (TLS 1.2+).',
  '- Maintain audit logs of all privileged access and configuration changes.',
  '',
  '### Availability',
  '',
  'Availability criteria focus on system uptime and recovery. Engineers must:',
  '',
  '- Define and track SLAs for all customer-facing services.',
  '- Implement automated alerting for downtime and performance degradation.',
  '- Test disaster recovery procedures at least annually and document results.',
  '- Maintain and test backups regularly.',
  '',
  '### Processing Integrity',
  '',
  'Ensure that system processing is complete, valid, accurate, and timely:',
  '',
  '- Implement input validation on all data entry points.',
  '- Use checksums or digital signatures for data integrity verification.',
  '- Monitor processing pipelines for errors and anomalies.',
  '',
  '## Evidence Engineering Teams Must Produce',
  '',
  'During a SOC 2 audit, engineers must provide:',
  '',
  '1. **Access control evidence**: Screenshots/exports of RBAC configurations, MFA enforcement settings, and access review logs.',
  '2. **Vulnerability management**: Scan results, patch records, and remediation timelines.',
  '3. **Change management**: Pull request approvals, deployment logs, and change tickets.',
  '4. **Encryption configs**: TLS certificate records, key management documentation.',
  '5. **Incident logs**: Documentation of security events, response timelines, and resolution notes.',
  '',
  'Automate evidence collection where possible using compliance tools integrated into CI/CD pipelines.',
  '',
  '## Developer Best Practices for SOC 2',
  '',
  '- **Code reviews are a control** — Require at least one reviewer approval before merging to main.',
  '- **Secrets management** — Never hardcode credentials. Use a secrets manager.',
  '- **Dependency scanning** — Run SCA tools on every build. Remediate high/critical CVEs promptly.',
  '- **Logging standards** — Include user IDs, timestamps, and action types in all audit-relevant log entries. Never log PII or secrets.',
  '- **Infrastructure as code** — Manage all infrastructure through IaC to ensure consistency and auditability.',
].join('\n')

const PHISHING_CONTENT = [
  '## The Phishing Landscape',
  '',
  'Phishing remains the number one initial attack vector for data breaches worldwide. Modern phishing attacks are sophisticated, personalized, and increasingly difficult to distinguish from legitimate communications. This module teaches you to recognize, respond to, and report phishing attempts.',
  '',
  '## Types of Phishing Attacks',
  '',
  '### Email Phishing',
  '',
  'The most common form. Attackers send mass emails impersonating trusted brands to harvest credentials or deliver malware.',
  '',
  '**Red flags:**',
  '- Sender address does not match the display name (hover to reveal the real address)',
  '- Generic greetings ("Dear Customer" instead of your name)',
  '- Urgent language demanding immediate action',
  '- Links that do not match the stated destination',
  '- Grammar and spelling errors',
  '- Unexpected attachments',
  '',
  '### Spear Phishing',
  '',
  'Targeted phishing using personal information about the victim. Attackers research their targets using LinkedIn, social media, and company websites to craft convincing messages.',
  '',
  '### Smishing (SMS Phishing)',
  '',
  'Phishing via text message. Common lures include package delivery notifications, bank alerts, and prize notifications.',
  '',
  '### Business Email Compromise (BEC)',
  '',
  'A high-value attack where adversaries compromise or spoof a business executive\'s email to authorize fraudulent wire transfers or redirect payroll.',
  '',
  '## Analyzing Suspicious Messages',
  '',
  'Before clicking anything, check:',
  '',
  '1. **Sender address** — Is the domain legitimate?',
  '2. **Link destinations** — Hover over links before clicking. Does the URL match what is displayed?',
  '3. **Attachments** — Were you expecting this file? Is the format unusual (.exe, .iso, .lnk)?',
  '4. **Request type** — Does this request make sense? Would your IT team really ask for your password via email?',
  '5. **Urgency** — Attackers create false urgency to prevent you from thinking critically.',
  '',
  '## Responding to Phishing Attempts',
  '',
  'If you receive a suspicious message:',
  '',
  '1. **Do not click links or open attachments.**',
  '2. **Do not reply** — even to unsubscribe.',
  '3. **Report it** using your organization\'s phishing report button or by forwarding to your security team.',
  '4. **Delete the message** after reporting.',
  '',
  'If you accidentally clicked:',
  '1. **Disconnect from the network** immediately.',
  '2. **Change your passwords** from a clean device.',
  '3. **Notify your security team immediately** — do not wait to see if something happens.',
].join('\n')

const ACCESS_CONTROL_CONTENT = [
  '## Why Access Control Matters',
  '',
  'Access control is the process of restricting who can view or use resources in your organization. Weak access controls are responsible for a significant proportion of data breaches.',
  '',
  'A robust access control program limits the blast radius of any compromise, ensures accountability, and supports compliance with frameworks including SOC 2, ISO 27001, HIPAA, and GDPR.',
  '',
  '## Core Principles',
  '',
  '### Principle of Least Privilege (PoLP)',
  '',
  'Every user, application, and system should have access only to the resources necessary for their job function — nothing more.',
  '',
  '**In practice:**',
  '- Grant permissions at the most granular level possible.',
  '- Default to no access; require justification to grant.',
  '- Regularly review permissions and remove what is no longer needed.',
  '- Avoid granting permanent admin access; use time-limited elevated privileges.',
  '',
  '### Separation of Duties (SoD)',
  '',
  'No single person should have sole control over a critical process or sensitive system. This reduces the risk of fraud and error.',
  '',
  '**Examples:**',
  '- The person who approves financial transactions should not be the same person who initiates them.',
  '- Developers should not have direct access to deploy to production without a change management process.',
  '',
  '### Zero Trust Architecture',
  '',
  'Zero Trust is a security model that assumes no user or device is inherently trusted, even those inside the corporate network.',
  '',
  '**Zero Trust principles:**',
  '- Verify explicitly — always authenticate and authorize, using all available data points.',
  '- Use least privilege access.',
  '- Assume breach — design as if an attacker is already inside the network.',
  '',
  '## Role-Based Access Control (RBAC)',
  '',
  'RBAC assigns permissions to roles rather than individuals. Users are assigned roles appropriate to their function.',
  '',
  '**Best practices:**',
  '- Define roles based on job function, not individual needs.',
  '- Limit the number of roles to prevent role explosion.',
  '- Review role definitions at least annually.',
  '',
  '## Privileged Access Management (PAM)',
  '',
  'Privileged accounts (admin, root, service accounts) pose the greatest risk if compromised. PAM controls aim to:',
  '',
  '- **Vault credentials** — Store privileged credentials in a secure vault with check-in/check-out processes.',
  '- **Record sessions** — Record privileged sessions for accountability and forensic investigation.',
  '- **Enforce just-in-time (JIT) access** — Grant elevated access only when needed and only for the duration required.',
  '- **Alert on anomalies** — Alert on unusual privileged account activity.',
  '',
  '## Access Review Process',
  '',
  'Regular access reviews ensure that access remains appropriate over time:',
  '',
  '1. **Quarterly reviews** for privileged access and high-risk systems.',
  '2. **Annual reviews** for standard user access.',
  '3. **Event-triggered reviews** when employees change roles, go on leave, or leave the organization.',
  '4. **Termination procedures** — Revoke all access within hours of an employee\'s departure.',
].join('\n')

const INCIDENT_RESPONSE_CONTENT = [
  '## What is a Security Incident?',
  '',
  'A security incident is any event that threatens the confidentiality, integrity, or availability of an organization\'s information or systems. Incidents range from malware infections and phishing successes to unauthorized data access and denial-of-service attacks.',
  '',
  'Effective incident response (IR) limits damage, reduces recovery time, and helps prevent recurrence. Having a documented IR plan that is regularly tested is a requirement of most major compliance frameworks.',
  '',
  '## The Incident Response Lifecycle',
  '',
  'The NIST Cybersecurity Framework defines four phases of incident response:',
  '',
  '### Phase 1: Preparation',
  '',
  'Prepare before incidents occur:',
  '- Develop and document the IR plan.',
  '- Define incident severity levels and escalation paths.',
  '- Establish an incident response team (IRT) with clear roles.',
  '- Configure logging, monitoring, and alerting.',
  '- Conduct tabletop exercises to test the plan.',
  '',
  '### Phase 2: Detection and Analysis',
  '',
  'Identify and confirm an incident:',
  '- Monitor security tools (SIEM, EDR, IDS/IPS) for alerts.',
  '- Analyze indicators of compromise (IoCs) — unusual login times, large data transfers, unexpected processes.',
  '- Classify the incident by type and severity.',
  '- Assign an incident owner and begin documentation in the incident log.',
  '',
  '**Common indicators of compromise:**',
  '- Multiple failed login attempts followed by success',
  '- Unexpected outbound connections to unknown IP addresses',
  '- Files modified or deleted without explanation',
  '- Unusual process execution or scheduled tasks',
  '- Antivirus/EDR alerts and detections',
  '',
  '### Phase 3: Containment, Eradication and Recovery',
  '',
  'Stop the spread and restore operations:',
  '',
  '**Short-term containment:**',
  '- Isolate affected systems from the network.',
  '- Block malicious IPs/domains at the firewall.',
  '- Disable compromised accounts.',
  '',
  '**Long-term containment:**',
  '- Apply patches to exploited vulnerabilities.',
  '- Remove malware artifacts (files, registry entries, scheduled tasks).',
  '- Restore from known-good backups if needed.',
  '',
  '**Recovery:**',
  '- Restore systems to normal operations gradually.',
  '- Monitor closely for signs of re-infection.',
  '- Validate that systems are clean before returning to production.',
  '',
  '### Phase 4: Post-Incident Activity',
  '',
  'Learn from every incident:',
  '- Conduct a post-incident review (PIR/post-mortem) within 2 weeks.',
  '- Document: what happened, how it was detected, how it was contained, what worked, what did not.',
  '- Identify root causes and contributing factors.',
  '- Update the IR plan, runbooks, and security controls based on lessons learned.',
  '',
  '## Communication During an Incident',
  '',
  'Clear communication is critical during incident response:',
  '',
  '- **Internal**: Notify relevant stakeholders (executive leadership, legal, HR) based on severity.',
  '- **External**: Regulatory notifications may be required (GDPR: 72 hours; HIPAA: 60 days).',
  '- **Customers**: If customer data is impacted, notify promptly and clearly.',
  '- **Law enforcement**: Engage for criminal activity or nation-state attacks.',
  '',
  '## Incident Severity Classification',
  '',
  '- **Critical**: Major breach or system compromise (e.g. Ransomware encrypting production data)',
  '- **High**: Significant impact or high risk (e.g. Confirmed unauthorized data access)',
  '- **Medium**: Moderate impact, contained (e.g. Phishing email clicked, credentials reset)',
  '- **Low**: Minimal impact (e.g. Blocked intrusion attempt)',
].join('\n')

interface ModuleSeed {
  title: string
  description: string
  content: string
  category: string
  estimatedMinutes: number
  difficulty: string
  passingScore: number
}

const MODULES: ModuleSeed[] = [
  {
    title: 'Security Awareness Fundamentals',
    description: 'Build a solid foundation in cybersecurity awareness. Learn to recognize threats, protect sensitive data, and follow security best practices in everyday work.',
    content: SEC_AWARENESS_CONTENT,
    category: 'Security Awareness',
    estimatedMinutes: 25,
    difficulty: 'beginner',
    passingScore: 70,
  },
  {
    title: 'GDPR Basics for Everyone',
    description: 'Understand the General Data Protection Regulation (GDPR), your obligations when handling personal data, data subject rights, and how to respond to data breaches.',
    content: GDPR_CONTENT,
    category: 'Privacy & Data Protection',
    estimatedMinutes: 30,
    difficulty: 'beginner',
    passingScore: 75,
  },
  {
    title: 'SOC 2 for Engineers',
    description: 'A technical deep-dive into SOC 2 Trust Service Criteria. Learn what engineers must do to support SOC 2 compliance in code, infrastructure, and operations.',
    content: SOC2_CONTENT,
    category: 'Compliance',
    estimatedMinutes: 40,
    difficulty: 'intermediate',
    passingScore: 80,
  },
  {
    title: 'Phishing Recognition and Defense',
    description: 'Learn to identify sophisticated phishing attacks including spear phishing, smishing, and business email compromise. Practice recognizing red flags and responding correctly.',
    content: PHISHING_CONTENT,
    category: 'Security Awareness',
    estimatedMinutes: 20,
    difficulty: 'beginner',
    passingScore: 75,
  },
  {
    title: 'Access Control Best Practices',
    description: 'Master the principles of least privilege, zero trust, role-based access control, and privileged access management. Essential for anyone who administers systems or handles user access.',
    content: ACCESS_CONTROL_CONTENT,
    category: 'Identity & Access',
    estimatedMinutes: 35,
    difficulty: 'intermediate',
    passingScore: 80,
  },
  {
    title: 'Incident Response Basics',
    description: 'Learn the lifecycle of a security incident, how to contain and eradicate threats, perform post-incident analysis, and improve your organization\'s security posture through lessons learned.',
    content: INCIDENT_RESPONSE_CONTENT,
    category: 'Incident Response',
    estimatedMinutes: 35,
    difficulty: 'intermediate',
    passingScore: 75,
  },
]

export async function seedTrainingModules() {
  console.log('Seeding training modules...')

  for (const mod of MODULES) {
    const existing = await db
      .select({ id: trainingModules.id })
      .from(trainingModules)
      .where(eq(trainingModules.title, mod.title))

    if (existing.length > 0) {
      console.log(`  Skipping (already exists): ${mod.title}`)
      continue
    }

    await db.insert(trainingModules).values({
      title: mod.title,
      description: mod.description,
      content: mod.content,
      contentType: 'text',
      estimatedMinutes: mod.estimatedMinutes,
      passingScore: mod.passingScore,
      isRequired: false,
      isActive: true,
      isBuiltIn: true,
      metadata: {
        category: mod.category,
        difficulty: mod.difficulty,
      },
    })
    console.log(`  Created: ${mod.title}`)
  }

  console.log('Done seeding training modules.')
}

// Run directly: npx tsx lib/db/seed/training-seed.ts
if (require.main === module) {
  seedTrainingModules()
    .then(() => process.exit(0))
    .catch((err: unknown) => {
      console.error(err)
      process.exit(1)
    })
}
