/**
 * NIST 800-53 Rev 5 Seed Script
 * Seeds the canonical_controls table with the full NIST 800-53 Rev 5 control catalog.
 *
 * Usage (standalone): DATABASE_URL=... npx tsx seed/seed-nist.ts
 * Usage (programmatic): import { seedNistControls } from './seed-nist'
 */

import { db as defaultDb } from '@/lib/db'
import { canonicalControls } from '@/lib/db/schema'

type NewCanonicalControl = {
  nistId: string
  family: string
  familyName: string
  title: string
  description: string
  priority: string
  baselineImpact: string
  isEnhancement: boolean
  relatedControls: string
}

const controls: NewCanonicalControl[] = [
  // ── AC — Access Control ──────────────────────────────────────────────────
  { nistId: 'AC-1',  family: 'AC', familyName: 'Access Control', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an access control policy and procedures that facilitate the implementation of the access control policy and associated controls.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'AC-2',  family: 'AC', familyName: 'Access Control', title: 'Account Management', description: 'Manage system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-5,AC-6,IA-2,IA-4,IA-5,IA-8' },
  { nistId: 'AC-3',  family: 'AC', familyName: 'Access Control', title: 'Access Enforcement', description: 'Enforce approved authorizations for logical access to information and system resources in accordance with applicable access control policies.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-4,AC-5,AC-6,AC-16,AC-17' },
  { nistId: 'AC-4',  family: 'AC', familyName: 'Access Control', title: 'Information Flow Enforcement', description: 'Enforce approved authorizations for controlling the flow of information within the system and between connected systems based on applicable policy.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-17,AC-19,SA-17,SC-7' },
  { nistId: 'AC-5',  family: 'AC', familyName: 'Access Control', title: 'Separation of Duties', description: 'Separate the duties of individuals to reduce the risk of malevolent activity without collusion.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-6,PE-3,PS-2' },
  { nistId: 'AC-6',  family: 'AC', familyName: 'Access Control', title: 'Least Privilege', description: 'Employ the principle of least privilege, allowing only authorized accesses necessary to accomplish assigned organizational tasks.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-5,CM-11,PL-2' },
  { nistId: 'AC-7',  family: 'AC', familyName: 'Access Control', title: 'Unsuccessful Logon Attempts', description: 'Enforce a limit of consecutive invalid logon attempts and automatically lock accounts when the limit is exceeded.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-9,AC-14,IA-5' },
  { nistId: 'AC-8',  family: 'AC', familyName: 'Access Control', title: 'System Use Notification', description: 'Display an approved system use notification message before granting access that provides privacy and security notices.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-14,PL-4,PS-6' },
  { nistId: 'AC-10', family: 'AC', familyName: 'Access Control', title: 'Concurrent Session Control', description: 'Limit the number of concurrent sessions for each system account.', priority: 'P3', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'SC-23' },
  { nistId: 'AC-11', family: 'AC', familyName: 'Access Control', title: 'Device Lock', description: 'Prevent further access to the system by initiating a session lock after a period of inactivity.', priority: 'P3', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-7,PL-4' },
  { nistId: 'AC-12', family: 'AC', familyName: 'Access Control', title: 'Session Termination', description: 'Automatically terminate a user session after defined conditions or trigger events.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-11,MA-4,SC-10,SC-23' },
  { nistId: 'AC-14', family: 'AC', familyName: 'Access Control', title: 'Permitted Actions Without Identification or Authentication', description: 'Identify and document user actions that can be performed without identification or authentication.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-8,IA-2' },
  { nistId: 'AC-16', family: 'AC', familyName: 'Access Control', title: 'Security and Privacy Attributes', description: 'Support and maintain the binding of security and privacy attributes to information in storage, in process, and in transmission.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-3,AC-4,SC-16' },
  { nistId: 'AC-17', family: 'AC', familyName: 'Access Control', title: 'Remote Access', description: 'Establish and document usage restrictions, configuration and connection requirements, and implementation guidance for each type of remote access.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-4,AC-18,SC-10' },
  { nistId: 'AC-18', family: 'AC', familyName: 'Access Control', title: 'Wireless Access', description: 'Establish configuration requirements, connection requirements, and implementation guidance for wireless access.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-17,IA-2,SC-40' },
  { nistId: 'AC-19', family: 'AC', familyName: 'Access Control', title: 'Access Control for Mobile Devices', description: 'Establish configuration requirements, connection requirements, and implementation guidance for mobile devices.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-4,AC-7,AC-11,AC-17' },
  { nistId: 'AC-20', family: 'AC', familyName: 'Access Control', title: 'Use of External Systems', description: 'Verify that individuals using external systems comply with organizational security and privacy requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-17,CA-3,SA-9' },
  { nistId: 'AC-21', family: 'AC', familyName: 'Access Control', title: 'Information Sharing', description: 'Enable authorized users to determine whether access authorizations assigned to sharing partners match information access restrictions.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,PT-2,PT-7' },
  { nistId: 'AC-22', family: 'AC', familyName: 'Access Control', title: 'Publicly Accessible Content', description: 'Designate individuals authorized to post information onto a publicly accessible system and review proposed content.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-4,AU-13,SI-12' },
  { nistId: 'AC-23', family: 'AC', familyName: 'Access Control', title: 'Data Mining Protection', description: 'Employ data mining prevention and detection techniques to protect against unauthorized data mining.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-2,AC-3,SC-31' },
  { nistId: 'AC-24', family: 'AC', familyName: 'Access Control', title: 'Access Control Decisions', description: 'Establish procedures to ensure access control decisions are handled consistently and in a timely manner.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-2,AC-3' },
  { nistId: 'AC-25', family: 'AC', familyName: 'Access Control', title: 'Reference Monitor', description: 'Implement a reference monitor for the system that is tamperproof, always invoked, and small enough for analysis and testing.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-3,AC-16,SC-3' },

  // ── AT — Awareness and Training ─────────────────────────────────────────
  { nistId: 'AT-1', family: 'AT', familyName: 'Awareness and Training', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an awareness and training policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'AT-2', family: 'AT', familyName: 'Awareness and Training', title: 'Literacy Training and Awareness', description: 'Provide security and privacy literacy training to system users as part of initial training for new users.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-17,PL-4,PS-7' },
  { nistId: 'AT-3', family: 'AT', familyName: 'Awareness and Training', title: 'Role-Based Training', description: 'Provide role-based security and privacy training to personnel with assigned security roles and responsibilities.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,PL-4,PS-7,SA-3' },
  { nistId: 'AT-4', family: 'AT', familyName: 'Awareness and Training', title: 'Training Records', description: 'Document and monitor security and privacy training activities including awareness training and role-based training.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,PM-14' },
  { nistId: 'AT-5', family: 'AT', familyName: 'Awareness and Training', title: 'Contacts with Security Groups and Associations', description: 'Establish and institutionalize contact with selected groups and associations within the security community.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'SI-5' },
  { nistId: 'AT-6', family: 'AT', familyName: 'Awareness and Training', title: 'Training Feedback', description: 'Provide feedback on organizational security and privacy training results to foster improvement in individual and organizational performance.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AT-2,AT-3,AT-4' },

  // ── AU — Audit and Accountability ────────────────────────────────────────
  { nistId: 'AU-1',  family: 'AU', familyName: 'Audit and Accountability', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an audit and accountability policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'AU-2',  family: 'AU', familyName: 'Audit and Accountability', title: 'Event Logging', description: 'Identify the types of events that the system is capable of logging in support of the audit function.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-6,AC-17,AU-3,AU-12,SI-4' },
  { nistId: 'AU-3',  family: 'AU', familyName: 'Audit and Accountability', title: 'Content of Audit Records', description: 'Ensure that audit records contain information that establishes what type of event occurred, when and where it occurred, the source, outcome, and identity of individuals involved.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-2,AU-8,AU-12,SA-8' },
  { nistId: 'AU-4',  family: 'AU', familyName: 'Audit and Accountability', title: 'Audit Log Storage Capacity', description: 'Allocate audit log storage capacity to accommodate audit log retention requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-2,AU-5,AU-6,AU-11,SI-4' },
  { nistId: 'AU-5',  family: 'AU', familyName: 'Audit and Accountability', title: 'Response to Audit Logging Process Failures', description: 'Alert defined personnel in the event of an audit logging process failure and take additional defined actions.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-2,AU-4,SI-12' },
  { nistId: 'AU-6',  family: 'AU', familyName: 'Audit and Accountability', title: 'Audit Record Review, Analysis, and Reporting', description: 'Review and analyze system audit records for indications of inappropriate or unusual activity and report findings to designated officials.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AU-7,CA-7,IR-5,IR-6,SI-4' },
  { nistId: 'AU-7',  family: 'AU', familyName: 'Audit and Accountability', title: 'Audit Record Reduction and Report Generation', description: 'Provide an audit record reduction and report generation capability that supports analysis and reporting of audit information.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-6,IR-4' },
  { nistId: 'AU-8',  family: 'AU', familyName: 'Audit and Accountability', title: 'Time Stamps', description: 'Use internal system clocks to generate time stamps for audit records that can be mapped to UTC or GMT.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-3,AU-12' },
  { nistId: 'AU-9',  family: 'AU', familyName: 'Audit and Accountability', title: 'Protection of Audit Information', description: 'Protect audit information and audit tools from unauthorized access, modification, and deletion.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-6,MP-2,SI-3' },
  { nistId: 'AU-10', family: 'AU', familyName: 'Audit and Accountability', title: 'Non-Repudiation', description: 'Provide irrefutable evidence that an individual has performed a specific action on the system.', priority: 'P2', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-16,SA-8' },
  { nistId: 'AU-11', family: 'AU', familyName: 'Audit and Accountability', title: 'Audit Record Retention', description: 'Retain audit records for a defined time period to support after-the-fact investigations of security incidents.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-4,AU-5,AU-9,MP-6' },
  { nistId: 'AU-12', family: 'AU', familyName: 'Audit and Accountability', title: 'Audit Record Generation', description: 'Provide audit record generation capability for defined event types the system is capable of auditing.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-6,AC-17,AU-2,AU-3,SI-4' },
  { nistId: 'AU-13', family: 'AU', familyName: 'Audit and Accountability', title: 'Monitoring for Information Disclosure', description: 'Monitor external sources to determine if organizational information has been disclosed without authorization.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AU-6,SC-26' },
  { nistId: 'AU-14', family: 'AU', familyName: 'Audit and Accountability', title: 'Session Audit', description: 'Provide the capability for authorized users to select a session to capture and record or view.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-3,AU-3,AU-12' },
  { nistId: 'AU-16', family: 'AU', familyName: 'Audit and Accountability', title: 'Cross-Organizational Audit Logging', description: 'Employ methods for coordinating audit information requirements and management with external organizations.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AU-3,AU-6,AU-12' },

  // ── CA — Assessment, Authorization, and Monitoring ───────────────────────
  { nistId: 'CA-1', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an assessment, authorization, and monitoring policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'CA-2', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Control Assessments', description: 'Select the appropriate assessor or assessment team and develop a security and privacy assessment plan.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-5,CA-6,CA-7,RA-5,SA-11' },
  { nistId: 'CA-3', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Information Exchange', description: 'Approve and manage the exchange of information between the system and other systems using interconnection agreements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-4,AC-20,SA-9,SC-7' },
  { nistId: 'CA-5', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Plan of Action and Milestones', description: 'Develop a plan of action and milestones (POA&M) to document planned remediation actions to correct weaknesses noted during assessments.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-7,PM-4,RA-7,SI-2' },
  { nistId: 'CA-6', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Authorization', description: 'Assign a senior official as the authorizing official and ensure the system is authorized before commencing operations.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-3,CA-7,RA-3,SA-10' },
  { nistId: 'CA-7', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Continuous Monitoring', description: 'Develop a system-level continuous monitoring strategy and implement continuous monitoring in accordance with the organization-level strategy.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AU-6,CA-2,CA-5,CA-6,CM-3,RA-5' },
  { nistId: 'CA-8', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Penetration Testing', description: 'Conduct penetration testing to identify vulnerabilities that could be exploited by adversaries.', priority: 'P2', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'CA-2,RA-5,SA-11,SR-5,SR-6' },
  { nistId: 'CA-9', family: 'CA', familyName: 'Assessment, Authorization, and Monitoring', title: 'Internal System Connections', description: 'Authorize internal connections of system components to the system and document interface characteristics for each connection.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-4,CA-3,CM-2,SC-7' },

  // ── CM — Configuration Management ───────────────────────────────────────
  { nistId: 'CM-1',  family: 'CM', familyName: 'Configuration Management', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a configuration management policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'CM-2',  family: 'CM', familyName: 'Configuration Management', title: 'Baseline Configuration', description: 'Develop, document, and maintain under configuration control a current baseline configuration of the information system.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-9,CM-3,CM-6,CM-8,CM-9,SA-10' },
  { nistId: 'CM-3',  family: 'CM', familyName: 'Configuration Management', title: 'Configuration Change Control', description: 'Determine the types of changes to the system that are configuration-controlled and review proposed changes.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-7,CM-2,CM-4,CM-5,CM-6,SA-10,SI-2' },
  { nistId: 'CM-4',  family: 'CM', familyName: 'Configuration Management', title: 'Impact Analyses', description: 'Analyze changes to the system to determine potential security and privacy impacts prior to change implementation.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-7,CM-3,MA-2,SA-5,SA-10,SI-2' },
  { nistId: 'CM-5',  family: 'CM', familyName: 'Configuration Management', title: 'Access Restrictions for Change', description: 'Define, document, approve, and enforce physical and logical access restrictions associated with changes to the system.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-5,AC-6,CM-3,PE-3,SC-28' },
  { nistId: 'CM-6',  family: 'CM', familyName: 'Configuration Management', title: 'Configuration Settings', description: 'Establish and document configuration settings for system components that reflect the most restrictive mode consistent with operational requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-19,CM-2,CM-3,CM-7,SA-4,SI-2' },
  { nistId: 'CM-7',  family: 'CM', familyName: 'Configuration Management', title: 'Least Functionality', description: 'Configure the system to provide only essential capabilities and prohibit or restrict the use of functions, ports, protocols, software, and services not required.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,CM-2,CM-6,RA-5,SA-5,SC-7' },
  { nistId: 'CM-8',  family: 'CM', familyName: 'Configuration Management', title: 'System Component Inventory', description: 'Develop and document an inventory of system components that accurately reflects the system at the level of granularity deemed necessary.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-2,CM-7,PM-5,RA-2,SA-4,SI-2' },
  { nistId: 'CM-9',  family: 'CM', familyName: 'Configuration Management', title: 'Configuration Management Plan', description: 'Develop, document, and implement a configuration management plan for the system.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-2,CM-3,CM-4,CM-5,PL-2,SA-10' },
  { nistId: 'CM-10', family: 'CM', familyName: 'Configuration Management', title: 'Software Usage Restrictions', description: 'Use software and associated documentation in accordance with contract agreements and copyright laws.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-17,CM-7,CM-8,PM-10' },
  { nistId: 'CM-11', family: 'CM', familyName: 'Configuration Management', title: 'User-Installed Software', description: 'Establish policies governing the installation of software by users and enforce those policies through defined methods.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,CM-2,CM-5,CM-6,CM-7,CM-8,SI-4' },
  { nistId: 'CM-12', family: 'CM', familyName: 'Configuration Management', title: 'Information Location', description: 'Identify and document the location of information and system components on which the information is processed and stored.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-4,AC-6,CM-8,MP-1,PM-5,RA-2' },
  { nistId: 'CM-13', family: 'CM', familyName: 'Configuration Management', title: 'Data Action Mapping', description: 'Develop and document a map of system functions associated with the processing of personally identifiable information.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-4,CM-12,PT-2,PT-3,RA-8' },
  { nistId: 'CM-14', family: 'CM', familyName: 'Configuration Management', title: 'Signed Components', description: 'Prevent the installation of components without verification that the component is digitally signed using a recognized certificate.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CM-7,SI-7,SR-4' },

  // ── CP — Contingency Planning ─────────────────────────────────────────────
  { nistId: 'CP-1',  family: 'CP', familyName: 'Contingency Planning', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a contingency planning policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'CP-2',  family: 'CP', familyName: 'Contingency Planning', title: 'Contingency Plan', description: 'Develop a contingency plan for the system that identifies essential missions and business functions and provides recovery objectives and restoration priorities.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-3,CP-4,CP-6,CP-7,CP-8,CP-9,CP-10,IR-8,PM-8' },
  { nistId: 'CP-3',  family: 'CP', familyName: 'Contingency Planning', title: 'Contingency Training', description: 'Provide contingency training to system users consistent with assigned roles and responsibilities.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,CP-2,IR-2' },
  { nistId: 'CP-4',  family: 'CP', familyName: 'Contingency Planning', title: 'Contingency Plan Testing', description: 'Test the contingency plan at a defined frequency to determine effectiveness and organizational readiness.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,CP-2,CP-3,IR-3,PM-14' },
  { nistId: 'CP-6',  family: 'CP', familyName: 'Contingency Planning', title: 'Alternate Storage Site', description: 'Establish an alternate storage site including necessary agreements to permit the storage and retrieval of system backup information.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-7,CP-9,MP-4,MP-5' },
  { nistId: 'CP-7',  family: 'CP', familyName: 'Contingency Planning', title: 'Alternate Processing Site', description: 'Establish an alternate processing site and ensure equipment and supplies required to transfer and resume operations are available.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-6,CP-8,CP-9,CP-10,MA-6' },
  { nistId: 'CP-8',  family: 'CP', familyName: 'Contingency Planning', title: 'Telecommunications Services', description: 'Establish alternate telecommunications services to permit the resumption of operations for essential missions and business functions.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-6,CP-7' },
  { nistId: 'CP-9',  family: 'CP', familyName: 'Contingency Planning', title: 'System Backup', description: 'Conduct backups of user-level information, system-level information, and system documentation and store backup information at the alternate storage site.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-6,MP-4,MP-5,SI-3' },
  { nistId: 'CP-10', family: 'CP', familyName: 'Contingency Planning', title: 'System Recovery and Reconstitution', description: 'Provide for the recovery and reconstitution of the system to a known state after a disruption, compromise, or failure.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-6,CP-2,CP-4,CP-6,CP-7,CP-9,SC-24' },
  { nistId: 'CP-11', family: 'CP', familyName: 'Contingency Planning', title: 'Alternate Communications Protocols', description: 'Provide the capability to employ alternate communications protocols in support of maintaining continuity of operations.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CP-2,CP-8' },
  { nistId: 'CP-12', family: 'CP', familyName: 'Contingency Planning', title: 'Safe Mode', description: 'When anomalies are detected in system operation, provide the capability to switch the system to a mode with limited capabilities that are safer to operate.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CM-2,CP-10' },
  { nistId: 'CP-13', family: 'CP', familyName: 'Contingency Planning', title: 'Alternative Security Mechanisms', description: 'Employ alternative or supplemental security mechanisms for satisfying security requirements when the primary means is unavailable or compromised.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CP-2,CP-11' },

  // ── IA — Identification and Authentication ────────────────────────────────
  { nistId: 'IA-1',  family: 'IA', familyName: 'Identification and Authentication', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an identification and authentication policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'IA-2',  family: 'IA', familyName: 'Identification and Authentication', title: 'Identification and Authentication (Organizational Users)', description: 'Uniquely identify and authenticate organizational users and associate that identification with processes acting on behalf of those users.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-14,AC-17,IA-4,IA-5,IA-8' },
  { nistId: 'IA-3',  family: 'IA', familyName: 'Identification and Authentication', title: 'Device Identification and Authentication', description: 'Uniquely identify and authenticate devices before establishing a connection.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-17,AC-18,AC-19,CA-3,IA-4,IA-5' },
  { nistId: 'IA-4',  family: 'IA', familyName: 'Identification and Authentication', title: 'Identifier Management', description: 'Manage system identifiers by receiving authorization from defined personnel to assign an identifier and preventing reuse of identifiers for a defined time period.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,IA-2,IA-3,IA-5,IA-8,SC-37' },
  { nistId: 'IA-5',  family: 'IA', familyName: 'Identification and Authentication', title: 'Authenticator Management', description: 'Manage system authenticators by verifying the identity of the individual receiving the authenticator as part of the initial authenticator distribution.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,CM-6,IA-2,IA-3,IA-4,IA-7,IA-8,IA-9' },
  { nistId: 'IA-6',  family: 'IA', familyName: 'Identification and Authentication', title: 'Authentication Feedback', description: 'Obscure feedback of authentication information during the authentication process to protect the information from exploitation.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-18' },
  { nistId: 'IA-7',  family: 'IA', familyName: 'Identification and Authentication', title: 'Cryptographic Module Authentication', description: 'Implement mechanisms for authentication to a cryptographic module that meet applicable requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'IA-3,IA-5,SC-12,SC-13' },
  { nistId: 'IA-8',  family: 'IA', familyName: 'Identification and Authentication', title: 'Identification and Authentication (Non-Organizational Users)', description: 'Uniquely identify and authenticate non-organizational users or processes acting on behalf of non-organizational users.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-14,AC-17,IA-2,IA-4,IA-5' },
  { nistId: 'IA-9',  family: 'IA', familyName: 'Identification and Authentication', title: 'Service Identification and Authentication', description: 'Uniquely identify and authenticate services before establishing communications with such services.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'IA-3,IA-4,IA-5,SC-8' },
  { nistId: 'IA-10', family: 'IA', familyName: 'Identification and Authentication', title: 'Adaptive Authentication', description: 'Require individuals accessing the system to employ supplemental authentication techniques or mechanisms under specific circumstances.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'IA-2,IA-8' },
  { nistId: 'IA-11', family: 'IA', familyName: 'Identification and Authentication', title: 'Re-Authentication', description: 'Require users to re-authenticate when defined circumstances or situations requiring re-authentication occur.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-11,AC-12,IA-2,IA-3,IA-5' },
  { nistId: 'IA-12', family: 'IA', familyName: 'Identification and Authentication', title: 'Identity Proofing', description: 'Require that individuals undergo identity proofing as part of the user registration process with proof of identity.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-5,IA-1,IA-2,IA-4,IA-5' },
  { nistId: 'IA-13', family: 'IA', familyName: 'Identification and Authentication', title: 'Identity Provider', description: 'Establish and maintain a defined set of identity provider services for the federation of identity.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'IA-2,IA-4,IA-5' },

  // ── IR — Incident Response ────────────────────────────────────────────────
  { nistId: 'IR-1',  family: 'IR', familyName: 'Incident Response', title: 'Policy and Procedures', description: 'Develop, document, and disseminate an incident response policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'IR-2',  family: 'IR', familyName: 'Incident Response', title: 'Incident Response Training', description: 'Provide incident response training to system users consistent with assigned roles and responsibilities.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,CP-3,IR-3,IR-8' },
  { nistId: 'IR-3',  family: 'IR', familyName: 'Incident Response', title: 'Incident Response Testing', description: 'Test the incident response capability at a defined frequency to determine effectiveness and document the results.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-3,CP-4,IR-2,IR-8,PM-14' },
  { nistId: 'IR-4',  family: 'IR', familyName: 'Incident Response', title: 'Incident Handling', description: 'Implement an incident handling capability for security incidents that includes preparation, detection and analysis, containment, eradication, and recovery.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-19,AU-6,CP-2,CP-3,IR-2,IR-3,IR-6,IR-8,PE-6,SC-5,SC-7' },
  { nistId: 'IR-5',  family: 'IR', familyName: 'Incident Response', title: 'Incident Monitoring', description: 'Track and document incidents and maintain records about each incident, the status of the incident, and other information necessary for forensic investigations.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-6,IR-4,IR-8,PE-6,SI-3,SI-4' },
  { nistId: 'IR-6',  family: 'IR', familyName: 'Incident Response', title: 'Incident Reporting', description: 'Require personnel to report suspected incidents to the organizational incident response capability and report incident information to defined authorities.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-6,IR-4,IR-5,IR-8' },
  { nistId: 'IR-7',  family: 'IR', familyName: 'Incident Response', title: 'Incident Response Assistance', description: 'Provide an incident response support resource that offers advice and assistance to users for handling and reporting incidents.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,IR-4,IR-6,PM-22' },
  { nistId: 'IR-8',  family: 'IR', familyName: 'Incident Response', title: 'Incident Response Plan', description: 'Develop an incident response plan that provides a roadmap for implementing the incident response capability.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-4,IR-2,IR-3,IR-4,IR-7,PM-22' },
  { nistId: 'IR-9',  family: 'IR', familyName: 'Incident Response', title: 'Information Spillage Response', description: 'Respond to information spills by identifying the specific information involved in the contamination and taking defined corrective actions.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AU-4,CP-2,IR-3,IR-4,IR-6,IR-8' },
  { nistId: 'IR-10', family: 'IR', familyName: 'Incident Response', title: 'Integrated Information Security Analysis Team', description: 'Establish an integrated team of forensic and malicious code analysts, tool developers, and real-time operations personnel in response to incidents.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'IR-4,IR-6,IR-7,IR-8' },

  // ── MA — Maintenance ──────────────────────────────────────────────────────
  { nistId: 'MA-1', family: 'MA', familyName: 'Maintenance', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a maintenance policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'MA-2', family: 'MA', familyName: 'Maintenance', title: 'Controlled Maintenance', description: 'Schedule, document, and review records of maintenance and repairs on system components in accordance with manufacturer or vendor specifications.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-3,CM-4,MA-4,MP-6,PE-16,SA-12,SI-2' },
  { nistId: 'MA-3', family: 'MA', familyName: 'Maintenance', title: 'Maintenance Tools', description: 'Approve, control, and monitor the use of system maintenance tools and check tools for improper or unauthorized modifications.', priority: 'P3', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,MA-2,MA-5,PE-16' },
  { nistId: 'MA-4', family: 'MA', familyName: 'Maintenance', title: 'Nonlocal Maintenance', description: 'Approve and monitor nonlocal maintenance and diagnostic activities and require they be performed from a system implementing a comparable security level.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-6,AC-17,AU-2,IA-2,MA-2,MA-5,SC-7,SC-10' },
  { nistId: 'MA-5', family: 'MA', familyName: 'Maintenance', title: 'Maintenance Personnel', description: 'Establish a process for maintenance personnel authorization and maintain a list of authorized maintenance organizations or personnel.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,IA-2,IA-8,MA-4,MP-2,PE-2,PE-3,PS-7' },
  { nistId: 'MA-6', family: 'MA', familyName: 'Maintenance', title: 'Timely Maintenance', description: 'Obtain maintenance support and spare parts for defined system components within a defined time period of failure.', priority: 'P3', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-8,CP-7,SA-14,SA-15' },
  { nistId: 'MA-7', family: 'MA', familyName: 'Maintenance', title: 'Field Maintenance', description: 'Restrict or prohibit field maintenance on defined system components to only authorized maintenance personnel.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'MA-2,MA-5,PE-3' },

  // ── MP — Media Protection ─────────────────────────────────────────────────
  { nistId: 'MP-1', family: 'MP', familyName: 'Media Protection', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a media protection policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'MP-2', family: 'MP', familyName: 'Media Protection', title: 'Media Access', description: 'Restrict access to digital and non-digital media containing information to authorized individuals.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AU-9,PE-2,PE-3' },
  { nistId: 'MP-3', family: 'MP', familyName: 'Media Protection', title: 'Media Marking', description: 'Mark system media indicating distribution limitations, handling caveats, and applicable security markings of the information.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-16,CP-9,MP-2,MP-4,MP-5,RA-3' },
  { nistId: 'MP-4', family: 'MP', familyName: 'Media Protection', title: 'Media Storage', description: 'Physically control and securely store digital and non-digital media within controlled areas.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-19,CP-6,CP-9,MP-2,MP-7,PE-3' },
  { nistId: 'MP-5', family: 'MP', familyName: 'Media Protection', title: 'Media Transport', description: 'Protect and control digital and non-digital media during transport outside of controlled areas.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-7,AC-19,CP-2,CP-9,MP-3,MP-4,PE-16,SC-28' },
  { nistId: 'MP-6', family: 'MP', familyName: 'Media Protection', title: 'Media Sanitization', description: 'Sanitize digital and non-digital system media prior to disposal, release out of organizational control, or release for reuse.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'MA-2,MA-4,RA-3,SI-12' },
  { nistId: 'MP-7', family: 'MP', familyName: 'Media Protection', title: 'Media Use', description: 'Restrict or prohibit the use of defined types of system media on defined system components using defined controls.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-8,AC-19,PL-4,PM-12,SC-41' },
  { nistId: 'MP-8', family: 'MP', familyName: 'Media Protection', title: 'Media Downgrading', description: 'Establish processes to downgrade system media by sanitizing media from the higher security domain and verifying sanitization is effective.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'MP-6,SI-12' },

  // ── PE — Physical and Environmental Protection ────────────────────────────
  { nistId: 'PE-1',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a physical and environmental protection policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'PE-2',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Physical Access Authorizations', description: 'Develop, approve, and maintain a list of individuals with authorized access to the facility where the system resides.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-3,PE-4,PS-2,PS-3' },
  { nistId: 'PE-3',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Physical Access Control', description: 'Enforce physical access authorizations at defined entry and exit points to the facility where the system resides.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-5,AC-6,AU-2,PE-2,PE-4' },
  { nistId: 'PE-4',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Access Control for Transmission', description: 'Control physical access to system distribution and transmission lines within organizational facilities.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-2,PE-3,SC-8' },
  { nistId: 'PE-5',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Access Control for Output Devices', description: 'Control physical access to output devices to prevent unauthorized individuals from obtaining the output.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-2,PE-3,PE-4' },
  { nistId: 'PE-6',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Monitoring Physical Access', description: 'Monitor physical access to the facility to detect and respond to physical security incidents.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-2,AU-6,CA-7,IR-4,IR-6' },
  { nistId: 'PE-8',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Visitor Access Records', description: 'Maintain visitor access records to the facility and review visitor access records at a defined frequency.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-2,PE-3,PE-7' },
  { nistId: 'PE-9',  family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Power Equipment and Cabling', description: 'Protect power equipment and power cabling for the system from damage and destruction.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-10,PE-11,PE-12' },
  { nistId: 'PE-10', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Emergency Shutoff', description: 'Provide the capability of shutting off power to the system or individual components in emergency situations.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PE-9,PE-11,PE-12' },
  { nistId: 'PE-11', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Emergency Power', description: 'Provide an uninterruptible power supply to facilitate an orderly shutdown of the system in the event of a primary power source loss.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,CP-7,PE-9,PE-10' },
  { nistId: 'PE-12', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Emergency Lighting', description: 'Employ and maintain automatic emergency lighting that activates in the event of a power outage and covers emergency exits and evacuation routes.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,PE-9,PE-10,PE-11' },
  { nistId: 'PE-13', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Fire Protection', description: 'Employ and maintain fire detection and suppression systems supported by an independent energy source.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2' },
  { nistId: 'PE-14', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Environmental Controls', description: 'Maintain temperature and humidity levels within the facility at defined acceptable levels and monitor the levels at a defined frequency.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-3,CP-2' },
  { nistId: 'PE-15', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Water Damage Protection', description: 'Protect the system from water damage by providing master shutoff or isolation valves that are accessible and working properly.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2' },
  { nistId: 'PE-16', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Delivery and Removal', description: 'Authorize, monitor, and control entering and exiting facility components and maintain records of those items.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-3,CM-8,MA-2,MA-3,SA-12' },
  { nistId: 'PE-17', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Alternate Work Site', description: 'Determine and document allowed alternate work sites and employ the following controls at alternate work sites.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-17,AC-18,CP-7' },
  { nistId: 'PE-18', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Location of System Components', description: 'Position system components within the facility to minimize potential damage from physical and environmental hazards.', priority: 'P3', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'CP-2,PE-13,PE-14,PE-15,RA-5' },
  { nistId: 'PE-19', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Information Leakage', description: 'Protect the system from information leakage due to electromagnetic signals emanations.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PE-18,SC-8' },
  { nistId: 'PE-20', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Asset Monitoring and Tracking', description: 'Employ an asset tracking technology and controls to track and monitor the location and movement of hardware assets.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CM-8,PE-16' },
  { nistId: 'PE-21', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Electromagnetic Pulse Protection', description: 'Employ electromagnetic pulse (EMP) protection for defined systems and system components.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CP-2,PE-9' },
  { nistId: 'PE-22', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Component Marking', description: 'Mark system components using defined markings indicating the impact level or classification level of the information permitted to be processed.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-16,MP-3,PE-16' },
  { nistId: 'PE-23', family: 'PE', familyName: 'Physical and Environmental Protection', title: 'Facility Location', description: 'Plan the location or site of the facility with regard to physical and environmental hazards and consider such hazards in the risk mitigation strategy.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CP-2,PE-18,RA-3' },

  // ── PL — Planning ─────────────────────────────────────────────────────────
  { nistId: 'PL-1',  family: 'PL', familyName: 'Planning', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a planning policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'PL-2',  family: 'PL', familyName: 'Planning', title: 'System Security and Privacy Plans', description: 'Develop security and privacy plans for the system that describe security and privacy requirements and the controls in place or planned for meeting those requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-6,AC-14,CA-2,CA-3,CA-7,CM-9,CP-2,IR-8,MA-4,PL-8,SA-5' },
  { nistId: 'PL-4',  family: 'PL', familyName: 'Planning', title: 'Rules of Behavior', description: 'Establish and provide to individuals requiring access to the system the rules that describe their responsibilities and expected behavior.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-8,AC-9,AT-2,AT-3,CM-11,IA-2,MP-7,SI-12' },
  { nistId: 'PL-7',  family: 'PL', familyName: 'Planning', title: 'Concept of Operations', description: 'Develop a concept of operations (CONOPS) for the system describing how the organization intends to operate the system from an information security and privacy perspective.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PL-2,SA-4' },
  { nistId: 'PL-8',  family: 'PL', familyName: 'Planning', title: 'Security and Privacy Architectures', description: 'Develop security and privacy architectures for the system that describes the overall philosophy, requirements, and approach to protecting confidentiality, integrity, and availability.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PL-2,PM-7,RA-3,SA-3,SA-8,SA-17' },
  { nistId: 'PL-9',  family: 'PL', familyName: 'Planning', title: 'Central Management', description: 'Centrally manage defined controls and control enhancements as an organization-wide policy.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PL-2' },
  { nistId: 'PL-10', family: 'PL', familyName: 'Planning', title: 'Baseline Selection', description: 'Select a control baseline for the system.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CA-2,RA-2,RA-3' },
  { nistId: 'PL-11', family: 'PL', familyName: 'Planning', title: 'Baseline Tailoring', description: 'Tailor the selected control baseline by applying specified tailoring actions.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PL-10,RA-2,RA-3' },

  // ── PM — Program Management ───────────────────────────────────────────────
  { nistId: 'PM-1',  family: 'PM', familyName: 'Program Management', title: 'Information Security Program Plan', description: 'Develop and disseminate an organization-wide information security program plan that provides an overview of the requirements for the security program.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,PL-2,PM-8,SA-1' },
  { nistId: 'PM-2',  family: 'PM', familyName: 'Program Management', title: 'Information Security Program Leadership Roles', description: 'Appoint a senior agency information security officer with the mission and resources to coordinate, develop, implement, and maintain an organization-wide information security program.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,PM-1' },
  { nistId: 'PM-3',  family: 'PM', familyName: 'Program Management', title: 'Information Security and Privacy Resources', description: 'Include the resources needed to implement the information security and privacy programs in capital planning and investment requests.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-1,PM-2,SA-2' },
  { nistId: 'PM-4',  family: 'PM', familyName: 'Program Management', title: 'Plan of Action and Milestones Process', description: 'Implement a process for ensuring plans of action and milestones for security and privacy programs and associated systems are developed and maintained.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-5,PM-3' },
  { nistId: 'PM-5',  family: 'PM', familyName: 'Program Management', title: 'System Inventory', description: 'Develop and update at a defined frequency an inventory of organizational systems.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-6,CM-8,PM-8' },
  { nistId: 'PM-6',  family: 'PM', familyName: 'Program Management', title: 'Measures of Performance', description: 'Develop, monitor, and report on the results of information security and privacy measures of performance.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-7,PM-1,RA-2' },
  { nistId: 'PM-7',  family: 'PM', familyName: 'Program Management', title: 'Enterprise Architecture', description: 'Develop an enterprise architecture with consideration for information security and privacy and the resulting risk.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PL-2,PL-8,PM-5,SA-3,SA-17' },
  { nistId: 'PM-8',  family: 'PM', familyName: 'Program Management', title: 'Critical Infrastructure Plan', description: 'Address information security and privacy issues in the development, documentation, and updating of a critical infrastructure protection plan.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-1,PM-7,RA-3,SA-14' },
  { nistId: 'PM-9',  family: 'PM', familyName: 'Program Management', title: 'Risk Management Strategy', description: 'Develop a comprehensive strategy to manage security and privacy risk to organizational operations and assets.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-1,RA-3' },
  { nistId: 'PM-10', family: 'PM', familyName: 'Program Management', title: 'Authorization Process', description: 'Manage the security and privacy state of organizational systems and environments through authorization processes.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-6,PM-9' },
  { nistId: 'PM-11', family: 'PM', familyName: 'Program Management', title: 'Mission and Business Process Definition', description: 'Define organizational mission and business processes with consideration for information security and privacy and the resulting risk.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CP-2,PM-7,PM-8' },

  // ── PS — Personnel Security ───────────────────────────────────────────────
  { nistId: 'PS-1', family: 'PS', familyName: 'Personnel Security', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a personnel security policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'PS-2', family: 'PS', familyName: 'Personnel Security', title: 'Position Risk Designation', description: 'Assign a risk designation to all organizational positions and establish screening criteria for individuals filling those positions.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-5,PE-2,PE-3,PL-2,PS-3,PS-7,SA-21' },
  { nistId: 'PS-3', family: 'PS', familyName: 'Personnel Security', title: 'Personnel Screening', description: 'Screen individuals prior to authorizing access to the system and rescreen individuals according to a defined condition or frequency.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,IA-4,PM-12,PS-2,SA-21' },
  { nistId: 'PS-4', family: 'PS', familyName: 'Personnel Security', title: 'Personnel Termination', description: 'Upon termination of individual employment, disable system access, terminate and revoke authenticators and credentials, and notify defined personnel.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,IA-4,PE-2,PM-12,PS-5,PS-6' },
  { nistId: 'PS-5', family: 'PS', familyName: 'Personnel Security', title: 'Personnel Transfer', description: 'Review and confirm ongoing operational need for current logical and physical access authorizations when individuals are reassigned or transferred.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,IA-4,PE-2,PM-12,PS-4' },
  { nistId: 'PS-6', family: 'PS', familyName: 'Personnel Security', title: 'Access Agreements', description: 'Establish and document access agreements for organizational systems and ensure individuals sign appropriate access agreements prior to being granted access.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-17,PE-2,PL-4,PS-2,PS-3,PS-7,SA-21' },
  { nistId: 'PS-7', family: 'PS', familyName: 'Personnel Security', title: 'External Personnel Security', description: 'Establish personnel security requirements including security roles and responsibilities for external providers.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,PS-2,PS-3,PS-4,PS-5,PS-6,SA-9' },
  { nistId: 'PS-8', family: 'PS', familyName: 'Personnel Security', title: 'Personnel Sanctions', description: 'Employ a formal sanctions process for individuals failing to comply with established information security and privacy policies and procedures.', priority: 'P3', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PL-4,PS-6' },
  { nistId: 'PS-9', family: 'PS', familyName: 'Personnel Security', title: 'Position Descriptions', description: 'Establish and document security and privacy roles and responsibilities within position descriptions.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PM-2,PS-2' },

  // ── PT — PII Processing and Transparency ────────────────────────────────
  { nistId: 'PT-1', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a personally identifiable information processing and transparency policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'PT-2', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Authority to Process Personally Identifiable Information', description: 'Determine and document the legal authority that permits the collection, use, maintenance, and sharing of personally identifiable information.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,CM-13,PT-3,PT-4,PT-5,PT-6' },
  { nistId: 'PT-3', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Personally Identifiable Information Processing Purposes', description: 'Identify and document the purpose(s) for which personally identifiable information is processed and only process PII for identified and documented purposes.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,CM-13,PT-2,PT-5,RA-8' },
  { nistId: 'PT-4', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Consent', description: 'Implement a process to obtain consent from individuals prior to any new uses or disclosure of previously collected personally identifiable information.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PT-2,PT-5,PT-7' },
  { nistId: 'PT-5', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Privacy Notice', description: 'Provide notice to individuals about the processing of personally identifiable information that informs individuals about the authorities, purposes, and uses.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PT-2,PT-3,PT-4,PT-7' },
  { nistId: 'PT-6', family: 'PT', familyName: 'PII Processing and Transparency', title: 'System of Records Notice', description: 'Publish a system of records notice including a description of the individually identifiable information the agency plans to collect and the purposes for such activities.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PT-2,PT-3,PT-5' },
  { nistId: 'PT-7', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Specific Categories of Personally Identifiable Information', description: 'Apply defined processing conditions for specific categories of personally identifiable information.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PT-2,PT-3,RA-3' },
  { nistId: 'PT-8', family: 'PT', familyName: 'PII Processing and Transparency', title: 'Computer Matching Requirements', description: 'When a computer matching program is established, develop adequate advance notice of the program.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PT-2,PT-6' },

  // ── RA — Risk Assessment ──────────────────────────────────────────────────
  { nistId: 'RA-1',  family: 'RA', familyName: 'Risk Assessment', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a risk assessment policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'RA-2',  family: 'RA', familyName: 'Risk Assessment', title: 'Security Categorization', description: 'Categorize the system and information it processes, stores, and transmits in accordance with applicable laws, executive orders, directives, regulations, policies, standards, and guidelines.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-8,MP-4,PL-2,PM-5,SA-8,SC-7' },
  { nistId: 'RA-3',  family: 'RA', familyName: 'Risk Assessment', title: 'Risk Assessment', description: 'Conduct a risk assessment including the likelihood and magnitude of harm from unauthorized access, use, disclosure, disruption, modification, or destruction of the organization.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-3,CA-6,CM-4,CP-6,CP-7,IA-8,PE-3,PL-2,PM-9,RA-2,SA-8,SC-38' },
  { nistId: 'RA-5',  family: 'RA', familyName: 'Risk Assessment', title: 'Vulnerability Monitoring and Scanning', description: 'Monitor and scan for vulnerabilities in the system and hosted applications at a defined frequency.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,CA-7,CA-8,CM-4,CM-6,RA-2,RA-3,SA-5,SA-11,SI-2,SI-3' },
  { nistId: 'RA-6',  family: 'RA', familyName: 'Risk Assessment', title: 'Technical Surveillance Countermeasures Survey', description: 'Employ a technical surveillance countermeasures (TSCM) survey at defined locations.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AC-3,IR-4,PE-4' },
  { nistId: 'RA-7',  family: 'RA', familyName: 'Risk Assessment', title: 'Risk Response', description: 'Respond to findings from security and privacy assessments, monitoring, and audits in accordance with organizational risk tolerance.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-5,CA-7,PM-4,RA-3' },
  { nistId: 'RA-8',  family: 'RA', familyName: 'Risk Assessment', title: 'Privacy Impact Assessments', description: 'Conduct privacy impact assessments for systems, programs, or other activities that pose a privacy risk.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-4,CM-9,CM-13,PT-2,PT-3,RA-3' },
  { nistId: 'RA-9',  family: 'RA', familyName: 'Risk Assessment', title: 'Criticality Analysis', description: 'Identify critical system components and functions by performing a criticality analysis at defined decision points in the system development life cycle.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CP-2,PL-2,PM-1,RA-2,RA-3,SA-14,SA-15' },
  { nistId: 'RA-10', family: 'RA', familyName: 'Risk Assessment', title: 'Threat Hunting', description: 'Establish and maintain a cyber threat hunting capability to search for indicators of compromise in organizational systems.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CA-2,CA-7,IR-4,IR-5,RA-3,RA-5,SI-4' },

  // ── SA — System and Services Acquisition ─────────────────────────────────
  { nistId: 'SA-1',  family: 'SA', familyName: 'System and Services Acquisition', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a system and services acquisition policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'SA-2',  family: 'SA', familyName: 'System and Services Acquisition', title: 'Allocation of Resources', description: 'Determine the high-level information security and privacy requirements for the system or system service in mission and business process planning.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-3,PM-11' },
  { nistId: 'SA-3',  family: 'SA', familyName: 'System and Services Acquisition', title: 'System Development Life Cycle', description: 'Acquire, develop, and manage the system using a system development life cycle that incorporates information security and privacy considerations.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-3,PM-7,SA-4,SA-5,SA-8,SR-3' },
  { nistId: 'SA-4',  family: 'SA', familyName: 'System and Services Acquisition', title: 'Acquisition Process', description: 'Include security and privacy requirements, descriptions, and criteria explicitly or by reference in acquisition contracts.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-6,CM-8,PS-7,SA-3,SA-5,SA-8,SA-11,SA-15,SA-16,SA-17,SR-3' },
  { nistId: 'SA-5',  family: 'SA', familyName: 'System and Services Acquisition', title: 'System Documentation', description: 'Obtain or develop administrator documentation for the system describing secure configuration, installation, and operation.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-6,CM-7,CM-8,PL-2,SA-3,SA-4,SA-8' },
  { nistId: 'SA-8',  family: 'SA', familyName: 'System and Services Acquisition', title: 'Security and Privacy Engineering Principles', description: 'Apply systems security and privacy engineering principles in the specification, design, development, implementation, and modification of the system.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'PL-8,RA-8,SA-3,SA-4,SA-17,SC-2,SC-3,SC-7' },
  { nistId: 'SA-9',  family: 'SA', familyName: 'System and Services Acquisition', title: 'External System Services', description: 'Require that providers of external system services comply with organizational security and privacy requirements.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-20,CA-3,CP-2,IR-7,PL-2,SA-2,SA-4,SR-3,SR-6' },
  { nistId: 'SA-10', family: 'SA', familyName: 'System and Services Acquisition', title: 'Developer Configuration Management', description: 'Require the developer of the system, component, or service to perform configuration management during development, implementation, and operation.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-3,CM-4,CM-7,CM-9,SA-4,SA-5,SA-8,SA-15,SI-2' },
  { nistId: 'SA-11', family: 'SA', familyName: 'System and Services Acquisition', title: 'Developer Testing and Evaluation', description: 'Require the developer to implement a security and privacy assessment plan and perform unit, integration, system, and regression testing.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,SA-3,SA-4,SA-5,SA-8,SA-15,SI-2,SR-5,SR-6' },
  { nistId: 'SA-12', family: 'SA', familyName: 'System and Services Acquisition', title: 'Memory Protection', description: 'Implement hardware-based and software-based mechanisms to detect and prevent unauthorized code execution in memory.', priority: 'P1', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'AC-25,SA-8,SC-3,SC-39,SI-16' },
  { nistId: 'SA-15', family: 'SA', familyName: 'System and Services Acquisition', title: 'Development Process, Standards, and Tools', description: 'Require the developer to follow a documented development process that explicitly addresses security and privacy requirements.', priority: 'P2', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'SA-3,SA-4,SA-8,SA-10,SA-11' },
  { nistId: 'SA-16', family: 'SA', familyName: 'System and Services Acquisition', title: 'Developer-Provided Training', description: 'Require the developer to provide training on the correct use and operation of implemented security and privacy functions, controls, and mechanisms.', priority: 'P2', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'AT-2,AT-3,SA-4,SA-5' },
  { nistId: 'SA-17', family: 'SA', familyName: 'System and Services Acquisition', title: 'Developer Security and Privacy Architecture and Design', description: 'Require the developer to produce a design specification and security and privacy architecture that accurately and completely describes required functionality.', priority: 'P2', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'PL-8,SA-3,SA-4,SA-8' },
  { nistId: 'SA-21', family: 'SA', familyName: 'System and Services Acquisition', title: 'Developer Screening', description: 'Require that the developer of the system, component, or service satisfy defined personnel screening criteria.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PS-3,SR-6' },
  { nistId: 'SA-22', family: 'SA', familyName: 'System and Services Acquisition', title: 'Unsupported System Components', description: 'Replace system components when support is no longer available from the developer, vendor, or manufacturer.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PL-2,SA-3' },
  { nistId: 'SA-23', family: 'SA', familyName: 'System and Services Acquisition', title: 'Specialization', description: 'Employ defined tailoring actions that provide defined levels of specialization for the system, system components, or system services.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PL-11,SA-8,SA-17' },

  // ── SC — System and Communications Protection ────────────────────────────
  { nistId: 'SC-1',  family: 'SC', familyName: 'System and Communications Protection', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a system and communications protection policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'SC-2',  family: 'SC', familyName: 'System and Communications Protection', title: 'Separation of System and User Functionality', description: 'Separate user functionality, including user interface services, from system management functionality.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-6,SA-8,SC-3,SC-22' },
  { nistId: 'SC-3',  family: 'SC', familyName: 'System and Communications Protection', title: 'Security Function Isolation', description: 'Isolate security functions from non-security functions.', priority: 'P1', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-6,SA-4,SA-8,SC-2,SC-7,SC-32' },
  { nistId: 'SC-4',  family: 'SC', familyName: 'System and Communications Protection', title: 'Information in Shared System Resources', description: 'Prevent unauthorized and unintended information transfer via shared system resources.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-4,SA-8,SC-2' },
  { nistId: 'SC-5',  family: 'SC', familyName: 'System and Communications Protection', title: 'Denial of Service Protection', description: 'Protect the system against the effects of defined types of denial-of-service events.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'SC-6,SC-7,SC-40' },
  { nistId: 'SC-7',  family: 'SC', familyName: 'System and Communications Protection', title: 'Boundary Protection', description: 'Monitor and control communications at external managed interfaces to the system and at key internal managed interfaces.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-4,AC-17,AC-18,CA-3,CM-2,CM-7,SA-8,SC-5,SC-26,SI-3' },
  { nistId: 'SC-8',  family: 'SC', familyName: 'System and Communications Protection', title: 'Transmission Confidentiality and Integrity', description: 'Implement cryptographic mechanisms to prevent unauthorized disclosure of information and detect changes during transmission.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-17,MA-4,PE-4,SA-4,SC-7,SC-13,SC-20' },
  { nistId: 'SC-10', family: 'SC', familyName: 'System and Communications Protection', title: 'Network Disconnect', description: 'Terminate the network connection associated with a communications session at the end of the session or after a defined period of inactivity.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-11,AC-12,SC-23' },
  { nistId: 'SC-12', family: 'SC', familyName: 'System and Communications Protection', title: 'Cryptographic Key Establishment and Management', description: 'Establish and manage cryptographic keys when cryptography is employed within the system.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'IA-7,SC-8,SC-13,SC-17,SC-28' },
  { nistId: 'SC-13', family: 'SC', familyName: 'System and Communications Protection', title: 'Cryptographic Protection', description: 'Implement the required types of cryptography for each specified cryptographic use.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-17,IA-3,IA-7,MA-4,MP-2,MP-4,SC-8,SC-12,SC-28' },
  { nistId: 'SC-15', family: 'SC', familyName: 'System and Communications Protection', title: 'Collaborative Computing Devices and Applications', description: 'Prohibit remote activation of collaborative computing devices and applications and provide an explicit indication of use to users.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-21' },
  { nistId: 'SC-17', family: 'SC', familyName: 'System and Communications Protection', title: 'Public Key Infrastructure Certificates', description: 'Issue public key certificates under an appropriate certificate policy or obtain certificates from an approved service provider.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'IA-5,SC-12' },
  { nistId: 'SC-18', family: 'SC', familyName: 'System and Communications Protection', title: 'Mobile Code', description: 'Define acceptable and unacceptable mobile code and mobile code technologies and authorize, monitor, and control the use of mobile code.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AU-2,AU-12,CM-2,CM-6,SI-3' },
  { nistId: 'SC-20', family: 'SC', familyName: 'System and Communications Protection', title: 'Secure Name/Address Resolution Service (Authoritative Source)', description: 'Provide additional data origin authentication and integrity verification artifacts along with authoritative name resolution data.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'SA-8,SC-8,SC-13,SC-21,SC-22' },
  { nistId: 'SC-21', family: 'SC', familyName: 'System and Communications Protection', title: 'Secure Name/Address Resolution Service (Recursive or Caching Resolver)', description: 'Request and perform data origin authentication and data integrity verification on name/address resolution responses.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'SC-20,SC-22' },
  { nistId: 'SC-22', family: 'SC', familyName: 'System and Communications Protection', title: 'Architecture and Provisioning for Name/Address Resolution Service', description: 'Ensure systems that collectively provide name/address resolution service are fault-tolerant and implement role separation.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'SC-2,SC-20,SC-21' },
  { nistId: 'SC-23', family: 'SC', familyName: 'System and Communications Protection', title: 'Session Authenticity', description: 'Protect the authenticity of communications sessions.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-11,AC-12,SC-8,SC-10' },
  { nistId: 'SC-24', family: 'SC', familyName: 'System and Communications Protection', title: 'Fail in Known State', description: 'Fail to a defined known state for defined types of failures on defined system components while preserving defined system state information.', priority: 'P1', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'CP-10,SC-7' },
  { nistId: 'SC-28', family: 'SC', familyName: 'System and Communications Protection', title: 'Protection of Information at Rest', description: 'Implement cryptographic mechanisms to prevent unauthorized disclosure and modification of information at rest.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-6,AC-19,CA-7,CM-3,PE-3,SC-8,SC-12,SC-13,SI-3,SI-7' },
  { nistId: 'SC-39', family: 'SC', familyName: 'System and Communications Protection', title: 'Process Isolation', description: 'Maintain a separate execution domain for each executing system process.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AC-4,AC-6,SA-8,SC-2,SC-3' },

  // ── SI — System and Information Integrity ─────────────────────────────────
  { nistId: 'SI-1',  family: 'SI', familyName: 'System and Information Integrity', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a system and information integrity policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8' },
  { nistId: 'SI-2',  family: 'SI', familyName: 'System and Information Integrity', title: 'Flaw Remediation', description: 'Identify, report, and correct information system flaws and test software and firmware updates related to flaw remediation.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-7,CM-3,CM-4,CM-5,CM-8,MA-2,RA-5,SA-8,SA-10,SA-11,SI-3,SI-5' },
  { nistId: 'SI-3',  family: 'SI', familyName: 'System and Information Integrity', title: 'Malicious Code Protection', description: 'Implement malicious code protection mechanisms at system entry and exit points to detect and eradicate malicious code.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-4,AC-19,AT-2,AU-2,CA-7,CM-3,IR-4,MA-4,RA-5,SA-4,SC-7,SI-2,SI-4,SI-7' },
  { nistId: 'SI-4',  family: 'SI', familyName: 'System and Information Integrity', title: 'System Monitoring', description: 'Monitor the system to detect attacks and indicators of potential attacks and unauthorized local, network, and remote connections.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-2,AC-3,AC-4,AC-8,AU-2,AU-6,CA-2,CA-7,CM-3,IA-3,IR-4,PE-3,RA-5,SC-7,SI-3' },
  { nistId: 'SI-5',  family: 'SI', familyName: 'System and Information Integrity', title: 'Security Alerts, Advisories, and Directives', description: 'Receive system security alerts, advisories, and directives from defined external organizations on an ongoing basis.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,IR-4,IR-6,SI-2' },
  { nistId: 'SI-6',  family: 'SI', familyName: 'System and Information Integrity', title: 'Security and Privacy Function Verification', description: 'Verify the correct operation of security and privacy functions on defined system components.', priority: 'P1', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'CA-7,CM-4,SA-11' },
  { nistId: 'SI-7',  family: 'SI', familyName: 'System and Information Integrity', title: 'Software, Firmware, and Information Integrity', description: 'Employ integrity verification tools to detect unauthorized changes to software, firmware, and information.', priority: 'P1', baselineImpact: 'HIGH', isEnhancement: false, relatedControls: 'AC-4,CM-3,CM-7,CM-8,MA-3,RA-5,SA-8,SA-9,SC-8,SC-28,SI-2,SI-3' },
  { nistId: 'SI-8',  family: 'SI', familyName: 'System and Information Integrity', title: 'Spam Protection', description: 'Employ spam protection mechanisms at system entry and exit points to detect and take action on unsolicited messages.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AT-2,IR-4,SI-3' },
  { nistId: 'SI-10', family: 'SI', familyName: 'System and Information Integrity', title: 'Information Input Validation', description: 'Check the validity of information inputs to defined system components.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-6,CM-6,SA-8' },
  { nistId: 'SI-11', family: 'SI', familyName: 'System and Information Integrity', title: 'Error Handling', description: 'Generate error messages that provide information necessary for corrective actions without revealing information that could be exploited.', priority: 'P2', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-3,AU-2,SI-2' },
  { nistId: 'SI-12', family: 'SI', familyName: 'System and Information Integrity', title: 'Information Management and Retention', description: 'Manage and retain information within the system in accordance with applicable laws, regulations, policies, and operational requirements.', priority: 'P2', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-16,AU-5,AU-11,CA-2,CA-3,CM-12' },
  { nistId: 'SI-16', family: 'SI', familyName: 'System and Information Integrity', title: 'Memory Protection', description: 'Implement defined controls to protect the system memory from unauthorized code execution.', priority: 'P1', baselineImpact: 'MODERATE,HIGH', isEnhancement: false, relatedControls: 'AC-25,SA-8,SA-12,SC-3' },

  // ── SR — Supply Chain Risk Management ────────────────────────────────────
  { nistId: 'SR-1',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Policy and Procedures', description: 'Develop, document, and disseminate a supply chain risk management policy and procedures.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'PM-9,PS-8,SI-12' },
  { nistId: 'SR-2',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Supply Chain Risk Management Plan', description: 'Develop a plan for managing supply chain risks associated with research, development, design, manufacturing, acquisition, delivery, integration, and operations.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,PM-9,RA-3,RA-9,SA-2,SA-3,SR-4' },
  { nistId: 'SR-3',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Supply Chain Controls and Processes', description: 'Establish a process to identify and address weaknesses or deficiencies in the supply chain elements and processes of defined systems.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CA-2,RA-3,RA-9,SA-2,SA-3,SA-4,SA-9,SR-2,SR-4,SR-5,SR-6' },
  { nistId: 'SR-4',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Provenance', description: 'Document, monitor, and maintain valid provenance of defined systems, system components, and associated data.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'CM-8,MA-2,MA-6,SA-3,SR-3,SR-5' },
  { nistId: 'SR-5',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Acquisition Strategies, Tools, and Methods', description: 'Employ defined acquisition strategies, contract tools, and procurement methods to protect against, identify, and mitigate supply chain risks.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'RA-9,SA-2,SA-4,SA-9,SA-12,SR-3,SR-6,SR-9,SR-10' },
  { nistId: 'SR-6',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Supplier Assessments and Reviews', description: 'Assess and review the supply chain-related risks associated with suppliers or contractors at a defined frequency.', priority: 'P1', baselineImpact: 'LOW,MODERATE,HIGH', isEnhancement: false, relatedControls: 'RA-3,RA-9,SR-3,SR-5' },
  { nistId: 'SR-7',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Supply Chain Operations Security', description: 'Employ operations security controls to protect supply chain-related information for the system, system component, or system service.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'SC-38,SR-3' },
  { nistId: 'SR-8',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Notification Agreements', description: 'Establish agreements and procedures with entities involved in the supply chain for notifying defined organizations about breaches and changes.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'IR-6,SR-3' },
  { nistId: 'SR-9',  family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Tamper Resistance and Detection', description: 'Implement a tamper protection program for the system, system component, or system service.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PE-3,SA-15,SI-7,SR-10' },
  { nistId: 'SR-10', family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Inspection of Systems or Components', description: 'Inspect defined systems or system components upon receipt to detect tampering.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'AT-3,PE-16,SR-9' },
  { nistId: 'SR-11', family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Component Authenticity', description: 'Develop and implement anti-counterfeit policy and procedures to detect and prevent counterfeit components from entering the system.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'PE-3,SA-4,SR-9,SR-10' },
  { nistId: 'SR-12', family: 'SR', familyName: 'Supply Chain Risk Management', title: 'Component Disposal', description: 'Dispose of components using defined techniques and methods.', priority: 'P0', baselineImpact: 'NOT_SELECTED', isEnhancement: false, relatedControls: 'CM-8,MP-6,SR-11' },
]

export async function seedNistControls(dbInstance?: typeof defaultDb) {
  const db = dbInstance ?? defaultDb
  console.log(`Seeding ${controls.length} NIST 800-53 Rev 5 controls...`)

  const batchSize = 50
  let inserted = 0

  for (let i = 0; i < controls.length; i += batchSize) {
    const batch = controls.slice(i, i + batchSize)
    await db
      .insert(canonicalControls)
      .values(batch)
      .onConflictDoUpdate({
        target: canonicalControls.nistId,
        set: {
          title: canonicalControls.title,
          updatedAt: new Date(),
        },
      })
    inserted += batch.length
    console.log(`  Inserted ${inserted}/${controls.length} controls...`)
  }

  console.log(`✓ Seeded ${inserted} NIST 800-53 Rev 5 controls successfully.`)
  return inserted
}

if (require.main === module) {
  seedNistControls()
    .then((count) => {
      console.log(`Seed complete: ${count} controls.`)
      process.exit(0)
    })
    .catch((err) => {
      console.error('Seed failed:', err)
      process.exit(1)
    })
}
