import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import {
  controls, controlAssignments, evidence, auditLogs,
  organizationFrameworks, frameworks, organizations, users,
} from '@/lib/db/schema'
import { eq, and, desc } from 'drizzle-orm'
import { requireAuth, ApiErrors } from '@/lib/api/auth-helper'
import archiver from 'archiver'
// stream import kept for future streaming use

// ── Helpers ───────────────────────────────────────────────────────────────────

function toCsv(rows: string[][]): string {
  return rows
    .map((row) =>
      row
        .map((cell) => {
          const str = cell == null ? '' : String(cell)
          if (str.includes(',') || str.includes('"') || str.includes('\n')) {
            return `"${str.replace(/"/g, '""')}"`
          }
          return str
        })
        .join(',')
    )
    .join('\n')
}

function stringToBuffer(str: string): Buffer {
  return Buffer.from(str, 'utf-8')
}

// ── Route ─────────────────────────────────────────────────────────────────────

// GET /api/audit/export-zip?frameworkId=xxx
// Returns a ZIP file containing audit package
export async function GET(req: NextRequest) {
  const session = await requireAuth(req)
  if (!session) return ApiErrors.unauthorized()
  if (!session.orgId) return ApiErrors.badRequest('No organisation associated with session')

  const { searchParams } = req.nextUrl
  const frameworkId = searchParams.get('frameworkId')

  const today = new Date().toISOString().split('T')[0]
  const filename = `audit-package-${today}.zip`
  const orgId = session.orgId as string

  try {
    // Get org info
    const [org] = await db
      .select({ name: organizations.name })
      .from(organizations)
      .where(eq(organizations.id, orgId))
      .limit(1)
    const orgName = org?.name ?? 'Unknown Org'

    // Determine frameworks
    let targetFrameworkIds: string[] = []
    if (frameworkId) {
      targetFrameworkIds = [frameworkId]
    } else {
      const orgFws = await db
        .select({ frameworkId: organizationFrameworks.frameworkId })
        .from(organizationFrameworks)
        .where(
          and(
            eq(organizationFrameworks.organizationId, orgId),
            eq(organizationFrameworks.isActive, true)
          )
        )
      targetFrameworkIds = orgFws.map((f) => f.frameworkId)
    }

    // Get framework details
    const fwDetails: Array<{ id: string; name: string; shortName: string | null }> = []
    for (const fwId of targetFrameworkIds) {
      const [fw] = await db
        .select({ id: frameworks.id, name: frameworks.name, shortName: frameworks.shortName })
        .from(frameworks)
        .where(eq(frameworks.id, fwId))
        .limit(1)
      if (fw) fwDetails.push(fw)
    }

    // Build zip in-memory using archiver
    const archive = archiver('zip', { zlib: { level: 6 } })
    const chunks: Buffer[] = []

    await new Promise<void>((resolve, reject) => {
      archive.on('data', (chunk: Buffer) => chunks.push(chunk))
      archive.on('end', resolve)
      archive.on('error', reject)

      // ── README.txt ────────────────────────────────────────
      const readmeLines = [
        `CompliGuard Audit Export Package`,
        `================================`,
        ``,
        `Organisation: ${orgName}`,
        `Export Date: ${today}`,
        `Frameworks: ${fwDetails.map((f) => f.shortName ?? f.name).join(', ') || 'All'}`,
        ``,
        `Contents`,
        `--------`,
        `README.txt               - This file`,
        `controls.csv             - All controls and their current status`,
        `evidence.csv             - All evidence metadata`,
        `audit-trail.csv          - Platform audit trail`,
        `frameworks/<name>/       - Per-framework data`,
        ``,
        `Generated by CompliGuard GRC Platform`,
        `Confidential — for authorised audit use only`,
      ].join('\n')

      archive.append(stringToBuffer(readmeLines), { name: 'README.txt' })

      // All processing wrapped in async IIFE
      ;(async () => {
        // ── Per-framework folders ─────────────────────────────

        for (const fw of fwDetails) {
          const safeName = (fw.shortName ?? fw.name).replace(/[^a-zA-Z0-9-_]/g, '_')
          const folder = `frameworks/${safeName}/`

          // Controls CSV for this framework
          const fwControls = await db
            .select({
              id: controls.id,
              controlId: controls.controlId,
              title: controls.title,
              category: controls.category,
              description: controls.description,
            })
            .from(controls)
            .where(eq(controls.frameworkId, fw.id))

          const ctrlHeaders = ['ControlRef', 'Title', 'Category', 'Status', 'EvidenceCount', 'Description']
          const ctrlRows: string[][] = [ctrlHeaders]

          for (const ctrl of fwControls) {
            const [assignment] = await db
              .select({ id: controlAssignments.id, status: controlAssignments.status })
              .from(controlAssignments)
              .where(
                and(
                  eq(controlAssignments.organizationId, orgId),
                  eq(controlAssignments.controlId, ctrl.id)
                )
              )
              .limit(1)

            let evidenceCount = 0
            if (assignment) {
              const evRows = await db
                .select({ id: evidence.id })
                .from(evidence)
                .where(eq(evidence.controlAssignmentId, assignment.id))
              evidenceCount = evRows.length
            }

            ctrlRows.push([
              ctrl.controlId ?? '',
              ctrl.title,
              ctrl.category ?? '',
              assignment?.status ?? 'not_started',
              String(evidenceCount),
              ctrl.description ?? '',
            ])
          }

          archive.append(stringToBuffer(toCsv(ctrlRows)), {
            name: `${folder}controls.csv`,
          })
        }

        // ── All controls + evidence metadata ──────────────────

        // Global controls CSV
        const allControlRows: string[][] = [['Framework', 'ControlRef', 'Title', 'Category', 'Status', 'EvidenceCount']]

        for (const fw of fwDetails) {
          const fwControls = await db
            .select({ id: controls.id, controlId: controls.controlId, title: controls.title, category: controls.category })
            .from(controls)
            .where(eq(controls.frameworkId, fw.id))

          for (const ctrl of fwControls) {
            const [assignment] = await db
              .select({ id: controlAssignments.id, status: controlAssignments.status })
              .from(controlAssignments)
              .where(and(eq(controlAssignments.organizationId, orgId), eq(controlAssignments.controlId, ctrl.id)))
              .limit(1)

            let evidenceCount = 0
            if (assignment) {
              const evRows = await db.select({ id: evidence.id }).from(evidence).where(eq(evidence.controlAssignmentId, assignment.id))
              evidenceCount = evRows.length
            }

            allControlRows.push([
              fw.shortName ?? fw.name,
              ctrl.controlId ?? '',
              ctrl.title,
              ctrl.category ?? '',
              assignment?.status ?? 'not_started',
              String(evidenceCount),
            ])
          }
        }

        archive.append(stringToBuffer(toCsv(allControlRows)), { name: 'controls.csv' })

        // Global evidence CSV
        const evidenceItems = await db
          .select({
            id: evidence.id,
            title: evidence.title,
            evidenceType: evidence.evidenceType,
            status: evidence.status,
            storageProvider: evidence.storageProvider,
            fileName: evidence.fileName,
            uploadedBy: evidence.uploadedBy,
            controlAssignmentId: evidence.controlAssignmentId,
            expiresAt: evidence.expiresAt,
            createdAt: evidence.createdAt,
          })
          .from(evidence)
          .where(eq(evidence.organizationId, orgId))
          .orderBy(desc(evidence.createdAt))
          .limit(5000)

        // Resolve uploaders
        const uploaderIds = [...new Set(evidenceItems.map((e) => e.uploadedBy).filter(Boolean))] as string[]
        const uploaderMap: Record<string, string> = {}
        for (const uid of uploaderIds) {
          const [user] = await db
            .select({ firstName: users.firstName, lastName: users.lastName, email: users.email })
            .from(users)
            .where(eq(users.id, uid))
            .limit(1)
          if (user) uploaderMap[uid] = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email
        }

        const evHeaders = ['Title', 'Type', 'Status', 'FileName', 'StorageProvider', 'UploadedBy', 'CreatedAt', 'ExpiresAt']
        const evRows: string[][] = [evHeaders]
        for (const ev of evidenceItems) {
          evRows.push([
            ev.title,
            ev.evidenceType,
            ev.status,
            ev.fileName ?? '',
            ev.storageProvider ?? '',
            ev.uploadedBy ? (uploaderMap[ev.uploadedBy] ?? ev.uploadedBy) : '',
            ev.createdAt.toISOString(),
            ev.expiresAt?.toISOString() ?? '',
          ])
        }
        archive.append(stringToBuffer(toCsv(evRows)), { name: 'evidence.csv' })

        // Audit trail CSV
        const logs = await db
          .select({
            id: auditLogs.id,
            userId: auditLogs.userId,
            action: auditLogs.action,
            resourceType: auditLogs.resourceType,
            resourceTitle: auditLogs.resourceTitle,
            description: auditLogs.description,
            ipAddress: auditLogs.ipAddress,
            createdAt: auditLogs.createdAt,
          })
          .from(auditLogs)
          .where(eq(auditLogs.organizationId, orgId))
          .orderBy(desc(auditLogs.createdAt))
          .limit(10000)

        const userIds = [...new Set(logs.map((l) => l.userId).filter(Boolean))] as string[]
        const userMap: Record<string, string> = {}
        for (const uid of userIds) {
          const [user] = await db
            .select({ firstName: users.firstName, lastName: users.lastName, email: users.email })
            .from(users)
            .where(eq(users.id, uid))
            .limit(1)
          if (user) userMap[uid] = [user.firstName, user.lastName].filter(Boolean).join(' ') || user.email
        }

        const auditHeaders = ['Timestamp', 'User', 'Action', 'EntityType', 'EntityTitle', 'IPAddress', 'Details']
        const auditRows: string[][] = [auditHeaders]
        for (const l of logs) {
          auditRows.push([
            l.createdAt.toISOString(),
            l.userId ? (userMap[l.userId] ?? l.userId) : '',
            l.action ?? '',
            l.resourceType ?? '',
            l.resourceTitle ?? '',
            l.ipAddress ?? '',
            l.description ?? '',
          ])
        }
        archive.append(stringToBuffer(toCsv(auditRows)), { name: 'audit-trail.csv' })

        // Finalize archive
        archive.finalize()
      })().catch(reject)
    })

    const zipBuffer = Buffer.concat(chunks)

    return new NextResponse(zipBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': String(zipBuffer.length),
        'Cache-Control': 'no-store',
      },
    })
  } catch (err) {
    console.error('[audit/export-zip]', err)
    return ApiErrors.internal()
  }
}
